book_name: "Z:\\Dropbox\\Documents\\SOOP\\YHT\\wms_ui_design\\00_drafts\\design\\entity_design\\devel\\entity_design.xlsx"
output: "Z:\\Dropbox\\Documents\\SOOP\\YHT\\wms_ui_design\\00_drafts\\design\\entity_design\\devel\\hoge.sql"
